<?php

namespace ContainerWL1a3xe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKmj_CodeManagerService extends Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer
{
    /**
     * Gets the public 'kmj.code_manager' shared autowired service.
     *
     * @return \Kematjaya\CodeManager\Manager\CodeManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Manager/CodeManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Manager/CodeManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Builder/CodeBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Builder/CodeBuilder.php';
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Repository/CodeLibraryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/tests/Repository/CodeLibraryRepository.php';

        return $container->services['kmj.code_manager'] = new \Kematjaya\CodeManager\Manager\CodeManager(($container->services['kmj.code_builder'] ?? ($container->services['kmj.code_builder'] = new \Kematjaya\CodeManager\Builder\CodeBuilder())), ($container->privates['Kematjaya\\CodeManager\\Repository\\CodeLibraryRepositoryInterface'] ?? ($container->privates['Kematjaya\\CodeManager\\Repository\\CodeLibraryRepositoryInterface'] = new \Kematjaya\CodeManagerBundle\Tests\Repository\CodeLibraryRepository())));
    }
}
