<?php

namespace ContainerWL1a3xe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKmj_CodeBuilderService extends Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer
{
    /**
     * Gets the public 'kmj.code_builder' shared autowired service.
     *
     * @return \Kematjaya\CodeManager\Builder\CodeBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Builder/CodeBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Builder/CodeBuilder.php';

        return $container->services['kmj.code_builder'] = new \Kematjaya\CodeManager\Builder\CodeBuilder();
    }
}
