services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\CodeManager\Builder\AbstractCodeBuilder:
        class: Kematjaya\CodeManager\Builder\CodeBuilder
        
    Kematjaya\CodeManager\Manager\CodeManagerInterface:
        class: Kematjaya\CodeManager\Manager\CodeManager
        
    Kematjaya\CodeManager\Manager\CodeLibraryLogManagerInterface:
        class: Kematjaya\CodeManager\Manager\CodeLibraryLogManager
        
    kmj.code_builder:
        alias: Kematjaya\CodeManager\Builder\AbstractCodeBuilder
        public: true
        
    kmj.code_manager:
        alias: Kematjaya\CodeManager\Manager\CodeManagerInterface
        public: true
        
    kmj.code_log_manager:
        alias: Kematjaya\CodeManager\Manager\CodeLibraryLogManagerInterface
        public: true
        
    Kematjaya\CodeManagerBundle\Listener\CodeManagerListener:
        class: Kematjaya\CodeManagerBundle\Listener\CodeManagerListener
        tags: 
            - { name: doctrine.event_listener, event: preFlush, priority: 1000 }
            
    Kematjaya\CodeManagerBundle\Repository\CodeLibraryRepository:
        class: Kematjaya\CodeManagerBundle\Repository\CodeLibraryRepository
        tags: 
            - doctrine.repository_service
            
    Kematjaya\CodeManagerBundle\Repository\CodeLibraryLogRepository:
        class: Kematjaya\CodeManagerBundle\Repository\CodeLibraryLogRepository
        tags: 
            - doctrine.repository_service