<?php

namespace ContainerCAscJfK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodeLibraryRepositoryInterfaceService extends Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer
{
    /**
     * Gets the private 'Kematjaya\CodeManager\Repository\CodeLibraryRepositoryInterface' shared service.
     *
     * @return \Kematjaya\CodeManagerBundle\Tests\Repository\CodeLibraryRepositoryTest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Repository/CodeLibraryRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/tests/Repository/CodeLibraryRepositoryTest.php';

        return $container->privates['Kematjaya\\CodeManager\\Repository\\CodeLibraryRepositoryInterface'] = new \Kematjaya\CodeManagerBundle\Tests\Repository\CodeLibraryRepositoryTest();
    }
}
