<?php

namespace ContainerCAscJfK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCodeLibraryLogRepositoryInterfaceService extends Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer
{
    /**
     * Gets the private 'Kematjaya\CodeManager\Repository\CodeLibraryLogRepositoryInterface' shared service.
     *
     * @return \Kematjaya\CodeManagerBundle\Tests\Repository\CodeLibraryLogRepositoryTest
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/kematjaya/code-manager/src/Repository/CodeLibraryLogRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/tests/Repository/CodeLibraryLogRepositoryTest.php';

        return $container->privates['Kematjaya\\CodeManager\\Repository\\CodeLibraryLogRepositoryInterface'] = new \Kematjaya\CodeManagerBundle\Tests\Repository\CodeLibraryLogRepositoryTest();
    }
}
