<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCAscJfK\Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCAscJfK/Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCAscJfK.legacy');

    return;
}

if (!\class_exists(Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer::class, false)) {
    \class_alias(\ContainerCAscJfK\Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer::class, Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer::class, false);
}

return new \ContainerCAscJfK\Kematjaya_CodeManagerBundle_Test_AppKernelTestTestDebugContainer([
    'container.build_hash' => 'CAscJfK',
    'container.build_id' => '8b17c661',
    'container.build_time' => 1608171532,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCAscJfK');
